<?php
// $Id$

/**
 * Plugins are described by creating a $plugin array which will be used
 * by the system that includes this file.
 */
$plugin = array(
  'title' => t('GameTracker'),
  'icon' => 'lgsl.png',
  'theme' => 'gameservers_gametracker',
  'css' => 'gametracker.css',
);

/**
 * Process variables for gameservers-lgsl.tpl.php.
 *
 * @see gameservers-lgsl.tpl.php
 */
/*
function gameservers_preprocess_gameservers_lgsl(&$variables) {
}
*/
