<?php
// $Id$

/**
 * Plugins are described by creating a $plugin array which will be used
 * by the system that includes this file.
 */
$plugin = array(
  'title' => t('LGSL Zone'),
  'icon' => 'lgsl.png',
  'theme' => 'gameservers_lgsl',
  'css' => 'lgsl.css',
);

/**
 * Process variables for gameservers-lgsl.tpl.php.
 *
 * @see gameservers-lgsl.tpl.php
 */
/*
function gameservers_preprocess_gameservers_lgsl(&$variables) {
}
*/
